/**
 * InputSystem
 *
 * Listens to keyboard events and exposes a clean, one-shot jump/restart API.
 * - One physical keypress → exactly one positive read from isJumpPressed().
 * - Browser key-repeat events (event.repeat === true) are ignored.
 * - destroy() cleanly removes all listeners using the stored bound references.
 */

const JUMP_KEYS = new Set(['Space', ' ', 'ArrowUp']);
const RESTART_KEYS = new Set(['Space', ' ', 'Enter']);

export class InputSystem {
  constructor() {
    this._jumpPending = false;
    this._restartPending = false;

    // Store bound references so the exact same function can be passed to
    // removeEventListener — inline lambdas would fail to unregister.
    this._onKeyDown = this._handleKeyDown.bind(this);
    this._onKeyUp = this._handleKeyUp.bind(this);
  }

  // ---------------------------------------------------------------------------
  // Lifecycle
  // ---------------------------------------------------------------------------

  /** Attach keyboard listeners to window. Safe to call once. */
  init() {
    window.addEventListener('keydown', this._onKeyDown);
    window.addEventListener('keyup', this._onKeyUp);
  }

  /** Remove all attached listeners. Leaves no memory leaks. */
  destroy() {
    window.removeEventListener('keydown', this._onKeyDown);
    window.removeEventListener('keyup', this._onKeyUp);
  }

  // ---------------------------------------------------------------------------
  // Public query API
  // ---------------------------------------------------------------------------

  /**
   * Returns true exactly once per physical key press of Space or ArrowUp.
   * Auto-resets after being read (consume-on-read pattern).
   * @returns {boolean}
   */
  isJumpPressed() {
    if (this._jumpPending) {
      this._jumpPending = false;
      return true;
    }
    return false;
  }

  /**
   * Returns true exactly once per physical key press of Space or Enter.
   * Used on the game-over screen to trigger a restart.
   * Auto-resets after being read.
   * @returns {boolean}
   */
  isRestartPressed() {
    if (this._restartPending) {
      this._restartPending = false;
      return true;
    }
    return false;
  }

  // ---------------------------------------------------------------------------
  // Private handlers
  // ---------------------------------------------------------------------------

  /** @param {KeyboardEvent} event */
  _handleKeyDown(event) {
    // Ignore browser key-repeat events generated by holding a key down.
    if (event.repeat) return;

    if (JUMP_KEYS.has(event.code) || JUMP_KEYS.has(event.key)) {
      this._jumpPending = true;
    }

    if (RESTART_KEYS.has(event.code) || RESTART_KEYS.has(event.key)) {
      this._restartPending = true;
    }
  }

  /** @param {KeyboardEvent} event */
  _handleKeyUp(event) {
    // keyup is tracked to keep the door open for future held-key mechanics
    // (e.g. duck). No action needed for jump/restart in MVP.
    void event;
  }
}

